"""
AI Text Detection Module

This module provides functionality to detect AI-generated text using various
detection methods and heuristics.
"""

from typing import Dict, List, Optional, Union
import re
import json


class AITextDetector:
    """
    A class to detect AI-generated text content.
    
    This detector uses various heuristics and patterns to identify text
    that may have been generated by AI systems.
    """
    
    def __init__(self):
        """Initialize the AI text detector with default patterns."""
        self.ai_patterns = [
            r"as an ai(?:\s+language)?\s+model",
            r"i(?:'m| am) an ai",
            r"i(?:'m| am) a language model",
            r"i don't have personal experiences",
            r"i don't have feelings",
            r"i can't provide personal opinions",
            r"as an artificial intelligence",
            r"i don't have the ability to",
            r"i'm not able to",
            r"i apologize, but i cannot",
            r"i understand you(?:'re| are) looking for",
        ]
        self.confidence_threshold = 0.7
    
    def detect(self, text: str) -> Dict[str, Union[bool, float, List[str]]]:
        """
        Detect if the given text is likely AI-generated.
        
        Args:
            text (str): The text to analyze
            
        Returns:
            Dict containing:
                - is_ai_generated: Boolean indicating if text appears to be AI-generated
                - confidence: Float between 0 and 1 indicating confidence level
                - matches: List of matched patterns
        """
        if not text or not isinstance(text, str):
            return {
                "is_ai_generated": False,
                "confidence": 0.0,
                "matches": []
            }
        
        text_lower = text.lower()
        matches = []
        
        # Check for AI-specific patterns
        for pattern in self.ai_patterns:
            if re.search(pattern, text_lower, re.IGNORECASE):
                matches.append(pattern)
        
        # Calculate confidence based on matches
        confidence = min(len(matches) * 0.5, 1.0)  # Increased from 0.3 to 0.5
        
        # Additional heuristics
        if self._check_formal_structure(text):
            confidence += 0.2
        
        if self._check_repetitive_patterns(text):
            confidence += 0.1
            
        # Boost confidence for multiple patterns
        if len(matches) >= 2:
            confidence += 0.2
        
        confidence = min(confidence, 1.0)
        
        return {
            "is_ai_generated": confidence >= self.confidence_threshold,
            "confidence": confidence,
            "matches": matches
        }
    
    def _check_formal_structure(self, text: str) -> bool:
        """Check if text has overly formal or structured patterns typical of AI."""
        formal_indicators = [
            r"first(?:ly)?[,:]",
            r"second(?:ly)?[,:]",
            r"third(?:ly)?[,:]",
            r"in conclusion[,:]",
            r"to summarize[,:]",
            r"it(?:'s| is) important to note",
            r"it(?:'s| is) worth mentioning",
        ]
        
        matches = sum(1 for pattern in formal_indicators 
                     if re.search(pattern, text.lower()))
        return matches >= 2
    
    def _check_repetitive_patterns(self, text: str) -> bool:
        """Check for repetitive sentence structures common in AI text."""
        sentences = re.split(r'[.!?]+', text)
        if len(sentences) < 3:
            return False
        
        # Check for similar sentence starters
        starters = [sentence.strip()[:20].lower() for sentence in sentences if sentence.strip()]
        unique_starters = set(starters)
        
        return len(unique_starters) < len(starters) * 0.7
    
    def set_confidence_threshold(self, threshold: float) -> None:
        """
        Set the confidence threshold for AI detection.
        
        Args:
            threshold (float): Threshold between 0 and 1
        """
        if 0 <= threshold <= 1:
            self.confidence_threshold = threshold
        else:
            raise ValueError("Threshold must be between 0 and 1")
    
    def add_pattern(self, pattern: str) -> None:
        """
        Add a custom pattern for AI detection.
        
        Args:
            pattern (str): Regular expression pattern to add
        """
        if pattern and pattern not in self.ai_patterns:
            self.ai_patterns.append(pattern)